---
- hosts: all
  become: true
  tasks:
  
  - name: Install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
  
  - name: Install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install unzip
    package:
       name: unzip

  - name: Install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    when: ansible_distribution in "CentOS, Ubuntu"

  - name: Copy Site HTML
    copy:
      src:  site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: ubuntu
  become: true
  tasks:

  - name: Install Apache & PHP on Ubuntu Server
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache & PHP on CentOS Servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS" 

