---
- hosts: all
  vars:
    http_port: 80
  become: true
  tasks:
  - name: Install the latest version of Apache & PHP
    package:
      name:
       -  httpd
       -  php
      state: latest
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
